import type { Person } from "@/lib/people/types";

/** Studio people — IDs align with legacy project team member ids (tm-*). */
export const mockPeople: Person[] = [
  {
    id: "tm-ahmed",
    nameAr: "نيمو",
    nameEn: "Ahmed Hassan",
    jobTitle: "Producer",
    jobDescription:
      "Owns production planning, crew coordination, and client delivery timelines across wedding and commercial lanes.",
    phone: "+20 100 111 2201",
    email: "nemo@sodavisuals.com",
    joinDate: "2023-03-01",
    status: "active",
    avatarUrl: "/avatars/nemo.svg",
    initials: "AH",
    createdAt: "2023-03-01T09:00:00.000Z",
  },
  {
    id: "tm-sara",
    nameAr: "سارة",
    nameEn: "Sara Nabil",
    jobTitle: "Lead Photographer",
    jobDescription:
      "Lead stills photographer for weddings and commercial hero days; owns lighting look and shot lists.",
    phone: "+20 100 111 2202",
    email: "sara@sodavisuals.com",
    joinDate: "2023-05-15",
    status: "active",
    initials: "SN",
    createdAt: "2023-05-15T09:00:00.000Z",
  },
  {
    id: "tm-karim",
    nameAr: "كريم",
    nameEn: "Karim Fouad",
    jobTitle: "Videographer",
    jobDescription:
      "Primary camera operator for motion; handles A-cam and client-facing on-set direction.",
    phone: "+20 100 111 2203",
    email: "karim@sodavisuals.com",
    joinDate: "2023-06-01",
    status: "active",
    initials: "KF",
    createdAt: "2023-06-01T09:00:00.000Z",
  },
  {
    id: "tm-layla",
    nameAr: "ليلى",
    nameEn: "Layla Mansour",
    jobTitle: "Editor",
    jobDescription:
      "Post-production lead — wedding films, commercial cutdowns, and revision cycles.",
    phone: "+20 100 111 2204",
    email: "layla@sodavisuals.com",
    joinDate: "2023-08-20",
    status: "active",
    initials: "LM",
    createdAt: "2023-08-20T09:00:00.000Z",
  },
  {
    id: "tm-omar",
    nameAr: "عمر",
    nameEn: "Omar Saleh",
    jobTitle: "Drone Operator",
    jobDescription:
      "Licensed drone pilot for aerials on compounds, weddings, and campaign exteriors.",
    phone: "+20 100 111 2205",
    email: "omar@sodavisuals.com",
    joinDate: "2024-01-10",
    status: "active",
    initials: "OS",
    createdAt: "2024-01-10T09:00:00.000Z",
  },
  {
    id: "tm-dina",
    nameAr: "دينا",
    nameEn: "Dina Farid",
    jobTitle: "Client Lead",
    jobDescription:
      "Client relationship owner — briefs, approvals, and commercial account follow-up.",
    phone: "+20 100 111 2206",
    email: "dina@sodavisuals.com",
    joinDate: "2024-02-01",
    status: "active",
    initials: "DF",
    createdAt: "2024-02-01T09:00:00.000Z",
  },
  {
    id: "tm-youssef",
    nameAr: "يوسف",
    nameEn: "Youssef Amir",
    jobTitle: "Lighting Tech",
    jobDescription:
      "Gaffer / lighting tech for studio and location days; maintains lighting kit.",
    phone: "+20 100 111 2207",
    email: "youssef@sodavisuals.com",
    joinDate: "2024-04-15",
    status: "active",
    initials: "YA",
    createdAt: "2024-04-15T09:00:00.000Z",
  },
  {
    id: "tm-nora",
    nameAr: "نورا",
    nameEn: "Nora Khalil",
    jobTitle: "Second Shooter",
    jobDescription:
      "Second photographer / B-cam for weddings and multi-unit commercial shoots.",
    phone: "+20 100 111 2208",
    email: "nora@sodavisuals.com",
    joinDate: "2024-09-01",
    status: "active",
    initials: "NK",
    createdAt: "2024-09-01T09:00:00.000Z",
  },
];
