export {
  SODA_OPERATOR,
  MODULE_SLOGANS,
  EMPTY_STATES,
  SUCCESS_MESSAGES,
  WARNING_MESSAGES,
  LOADING_MESSAGES,
  NOTIFICATION_COPY,
  DASHBOARD_SECTION_COPY,
  getDayPeriod,
  getGreeting,
  getModuleSlogan,
  getWorkspaceSlogan,
  extractVoiceSignals,
  deriveBusinessMood,
  getMoodMessage,
  getBriefCopy,
  getEmptyState,
  getSuccessMessage,
  getWarningMessage,
  getLoadingMessage,
} from "@/lib/brand/soda-voice";

export type {
  BriefCardCopy,
  BusinessMood,
  DashboardVoiceInput,
  DayPeriod,
  EmptyStateCopy,
  EmptyStateKey,
  LoadingKey,
  ModuleSloganKey,
  SuccessKey,
  VoiceSignals,
  WarningKey,
} from "@/lib/brand/types";
