export {
  SODA_OPERATOR,
  MODULE_SLOGANS,
  EMPTY_STATES,
  SUCCESS_MESSAGES,
  WARNING_MESSAGES,
  LOADING_MESSAGES,
  NOTIFICATION_COPY,
  DASHBOARD_SECTION_COPY,
  KPI_COPY,
  HUB_SECTION_COPY,
  toEasternDigits,
  getDayPeriod,
  getGreeting,
  getModuleSlogan,
  getWorkspaceSlogan,
  extractVoiceSignals,
  deriveBusinessMood,
  getMoodLabel,
  getMoodMessage,
  getBriefCopy,
  getEmptyState,
  getSuccessMessage,
  getWarningMessage,
  getLoadingMessage,
  getRevenueWhisper,
  getOutstandingWhisper,
  getActiveProjectsWhisper,
  getUpcomingShootsWhisper,
} from "@/lib/brand/soda-voice";

export { getTeamDisplayName } from "@/lib/brand/team-names";

export type {
  BriefAction,
  BriefCardCopy,
  BriefPriority,
  BriefSummaryStat,
  BusinessMood,
  DashboardSectionKey,
  DashboardVoiceInput,
  DayPeriod,
  EmptyStateCopy,
  EmptyStateKey,
  HubSectionCopyKey,
  KpiCopyKey,
  LoadingKey,
  ModuleSloganKey,
  SectionCopy,
  SuccessKey,
  VoiceSignals,
  WarningKey,
} from "@/lib/brand/types";
