import type { Quotation } from "@/lib/quotations/types";
import { snapshotFromQuotation } from "@/lib/quotations/utils";

const DEFAULT_TERMS_COMMERCIAL = [
  "Quotation valid for 21 days from issue date.",
  "Work begins after signed approval and deposit receipt.",
  "Usage rights limited to the scope described in deliverables.",
  "Revisions beyond the included rounds are billed separately.",
  "Payment terms as stated in the payment plan.",
].join("\n");

const DEFAULT_TERMS_WEDDING = [
  "Quotation valid for 14 days from issue date.",
  "Deposit confirms the shoot date and reserves the crew.",
  "Remaining balance due before final delivery.",
  "Travel outside Greater Cairo may incur additional fees.",
  "Raw files are not included unless listed as a line item.",
].join("\n");

function version(
  n: number,
  editedBy: string,
  editedAt: string,
  changeSummary: string,
  q: Quotation
) {
  return {
    version: n,
    editedBy,
    editedAt,
    changeSummary,
    snapshot: snapshotFromQuotation(q),
  };
}

/**
 * Realistic mock quotations across pipeline stages.
 * Line items only on quotes that have progressed past discovery.
 */
export const mockQuotations: Quotation[] = [
  {
    id: "quot-001",
    number: "QT-2026-0001",
    clientId: "client-016",
    clientName: "Last Step Footwear",
    company: "Last Step Footwear",
    contactName: "Nada Sherif",
    contactPhone: "+20 100 555 0101",
    contactEmail: "brand@laststep.eg",
    segment: "commercial",
    category: "Product campaign",
    estimatedValue: 185000,
    probability: 70,
    expectedClosingDate: "2026-07-20",
    assignedSales: "Sara Nabil",
    pipelineStage: "Sent",
    approvalStatus: "Sent",
    statusTimestamps: {
      Draft: "2026-06-18T10:00:00.000Z",
      "Waiting Review": "2026-06-22T14:00:00.000Z",
      Ready: "2026-06-24T09:00:00.000Z",
      Sent: "2026-06-25T11:30:00.000Z",
    },
    lastActivity: "2026-07-08T16:00:00.000Z",
    notes: "Fall lookbook + hero stills. Client reviewing usage rights.",
    attachments: [
      {
        id: "att-001",
        name: "LastStep_moodboard.pdf",
        type: "pdf",
        size: "2.4 MB",
        uploadedAt: "2026-06-20T12:00:00.000Z",
      },
    ],
    currentVersion: 2,
    projectInfo: {
      title: "Last Step Fall Campaign",
      location: "Studio + Zamalek street",
      shootDate: "2026-08-12",
      deliveryDate: "2026-09-05",
      workspaceId: "product",
      categoryDetail: "Footwear lookbook",
    },
    services: ["Photography", "Art direction support", "Retouching"],
    items: [
      {
        id: "li-001a",
        name: "Hero product stills (12 SKUs)",
        description: "White infinity + lifestyle variants",
        quantity: 12,
        unitPrice: 4500,
      },
      {
        id: "li-001b",
        name: "Campaign day rate (crew of 4)",
        quantity: 2,
        unitPrice: 28000,
      },
      {
        id: "li-001c",
        name: "Retouching package",
        quantity: 1,
        unitPrice: 35000,
      },
    ],
    optionalItems: [
      {
        id: "li-001o",
        name: "Motion cutdowns (15s / 30s)",
        quantity: 4,
        unitPrice: 8000,
      },
    ],
    discount: { type: "percent", value: 5 },
    taxRate: 14,
    timeline: {
      discoveryDate: "2026-06-15",
      shootDate: "2026-08-12",
      firstDeliveryDate: "2026-08-25",
      finalDeliveryDate: "2026-09-05",
    },
    deliverables: [
      "48 retouched stills",
      "Web + print crops",
      "Color-graded selects",
    ],
    paymentPlan: [
      {
        id: "pp-001a",
        label: "Deposit",
        percent: 40,
        amount: 74000,
        dueLabel: "On approval",
      },
      {
        id: "pp-001b",
        label: "Final",
        percent: 60,
        amount: 111000,
        dueLabel: "On delivery",
      },
    ],
    terms: DEFAULT_TERMS_COMMERCIAL,
    builderNotes: "Include brand guidelines PDF before shoot.",
    versions: [],
    createdAt: "2026-06-18T10:00:00.000Z",
    updatedAt: "2026-07-08T16:00:00.000Z",
  },
  {
    id: "quot-002",
    number: "QT-2026-0002",
    clientId: "client-009",
    clientName: "Karim & Dina",
    contactName: "Karim Hassan",
    contactPhone: "+20 106 445 3322",
    contactEmail: "karim.dina.wedding@email.com",
    segment: "wedding",
    category: "Full wedding coverage",
    estimatedValue: 95000,
    probability: 85,
    expectedClosingDate: "2026-07-15",
    assignedSales: "Layla Mansour",
    pipelineStage: "Client Feedback",
    approvalStatus: "Opened",
    statusTimestamps: {
      Draft: "2026-05-10T09:00:00.000Z",
      "Waiting Review": "2026-05-14T11:00:00.000Z",
      Sent: "2026-05-16T15:00:00.000Z",
      Opened: "2026-05-18T10:20:00.000Z",
    },
    lastActivity: "2026-07-09T09:30:00.000Z",
    notes: "Couple asked about second shooter and same-day teaser.",
    attachments: [],
    currentVersion: 3,
    projectInfo: {
      title: "Karim & Dina Wedding",
      location: "Four Seasons Nile Plaza",
      shootDate: "2026-09-20",
      deliveryDate: "2026-11-15",
      workspaceId: "weddings",
      categoryDetail: "Two-day celebration",
    },
    services: ["Photo", "Video", "Drone", "Same-day teaser"],
    items: [
      {
        id: "li-002a",
        name: "Full-day photo coverage",
        quantity: 1,
        unitPrice: 45000,
      },
      {
        id: "li-002b",
        name: "Cinematic highlight film",
        quantity: 1,
        unitPrice: 35000,
      },
      {
        id: "li-002c",
        name: "Same-day teaser",
        quantity: 1,
        unitPrice: 8000,
      },
      {
        id: "li-002d",
        name: "Drone package",
        quantity: 1,
        unitPrice: 7000,
      },
    ],
    optionalItems: [
      {
        id: "li-002o",
        name: "Second shooter",
        quantity: 1,
        unitPrice: 12000,
      },
    ],
    discount: { type: "fixed", value: 0 },
    taxRate: 0,
    timeline: {
      discoveryDate: "2026-05-08",
      shootDate: "2026-09-20",
      firstDeliveryDate: "2026-09-21",
      finalDeliveryDate: "2026-11-15",
      notes: "Teaser within 24h of reception.",
    },
    deliverables: [
      "Edited gallery (400+ images)",
      "Highlight film 4–6 min",
      "Same-day teaser",
    ],
    paymentPlan: [
      {
        id: "pp-002a",
        label: "Deposit",
        percent: 30,
        amount: 28500,
        dueLabel: "To hold date",
      },
      {
        id: "pp-002b",
        label: "Pre-shoot",
        percent: 40,
        amount: 38000,
        dueLabel: "14 days before",
      },
      {
        id: "pp-002c",
        label: "Final",
        percent: 30,
        amount: 28500,
        dueLabel: "On gallery delivery",
      },
    ],
    terms: DEFAULT_TERMS_WEDDING,
    builderNotes: "",
    versions: [],
    createdAt: "2026-05-10T09:00:00.000Z",
    updatedAt: "2026-07-09T09:30:00.000Z",
  },
  {
    id: "quot-003",
    number: "QT-2026-0003",
    clientId: "client-017",
    clientName: "Vodafone Egypt",
    company: "Vodafone Egypt",
    contactName: "Hossam Reda",
    contactEmail: "agency@vodafone.com.eg",
    segment: "commercial",
    category: "Brand film",
    estimatedValue: 420000,
    probability: 55,
    expectedClosingDate: "2026-08-01",
    assignedSales: "Ahmed Hassan",
    pipelineStage: "Internal Review",
    approvalStatus: "Waiting Review",
    statusTimestamps: {
      Draft: "2026-07-01T08:00:00.000Z",
      "Waiting Review": "2026-07-07T13:00:00.000Z",
    },
    lastActivity: "2026-07-07T13:00:00.000Z",
    notes: "Agency brief attached. Waiting Junior Soda sign-off on crew rates.",
    attachments: [
      {
        id: "att-003",
        name: "VF_brief_v2.pdf",
        type: "pdf",
        size: "1.1 MB",
        uploadedAt: "2026-07-01T10:00:00.000Z",
      },
    ],
    currentVersion: 1,
    projectInfo: {
      title: "Vodafone Summer Brand Film",
      location: "Cairo / Alexandria",
      shootDate: "2026-08-28",
      deliveryDate: "2026-09-30",
      workspaceId: "commercial",
    },
    services: ["Direction", "Production", "Post"],
    items: [
      {
        id: "li-003a",
        name: "Production day (full crew)",
        quantity: 3,
        unitPrice: 85000,
      },
      {
        id: "li-003b",
        name: "Post-production package",
        quantity: 1,
        unitPrice: 120000,
      },
      {
        id: "li-003c",
        name: "Licensing — 12 months digital",
        quantity: 1,
        unitPrice: 45000,
      },
    ],
    optionalItems: [],
    discount: { type: "percent", value: 0 },
    taxRate: 14,
    timeline: {
      shootDate: "2026-08-28",
      finalDeliveryDate: "2026-09-30",
    },
    deliverables: ["60s master", "3 cutdowns", "Stills package"],
    paymentPlan: [
      {
        id: "pp-003a",
        label: "Deposit",
        percent: 50,
        amount: 210000,
        dueLabel: "PO + deposit",
      },
      {
        id: "pp-003b",
        label: "Final",
        percent: 50,
        amount: 210000,
        dueLabel: "On delivery",
      },
    ],
    terms: DEFAULT_TERMS_COMMERCIAL,
    builderNotes: "Confirm talent buyout separately.",
    versions: [],
    createdAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-07T13:00:00.000Z",
  },
  {
    id: "quot-004",
    number: "QT-2026-0004",
    clientName: "Hana & Omar",
    contactName: "Hana Mostafa",
    contactPhone: "+20 101 222 3344",
    contactEmail: "hana.omar.wedding@email.com",
    segment: "wedding",
    category: "Engagement + wedding",
    estimatedValue: 72000,
    probability: 40,
    expectedClosingDate: "2026-07-25",
    assignedSales: "Layla Mansour",
    pipelineStage: "Discovery",
    approvalStatus: "Draft",
    statusTimestamps: {
      Draft: "2026-07-05T11:00:00.000Z",
    },
    lastActivity: "2026-07-06T18:00:00.000Z",
    notes: "Discovery call done. Awaiting venue confirmation before drafting.",
    attachments: [],
    currentVersion: 1,
    projectInfo: {
      title: "Hana & Omar Wedding Package",
      workspaceId: "weddings",
    },
    services: [],
    items: [],
    optionalItems: [],
    discount: { type: "percent", value: 0 },
    taxRate: 0,
    timeline: {},
    deliverables: [],
    paymentPlan: [],
    terms: DEFAULT_TERMS_WEDDING,
    builderNotes: "",
    versions: [],
    createdAt: "2026-07-05T11:00:00.000Z",
    updatedAt: "2026-07-06T18:00:00.000Z",
  },
  {
    id: "quot-005",
    number: "QT-2026-0005",
    clientId: "client-008",
    clientName: "Nile Foods Co.",
    company: "Nile Foods Co.",
    contactName: "Amr Fathy",
    contactEmail: "creative@nilefoods.eg",
    segment: "commercial",
    category: "Product photography",
    estimatedValue: 48000,
    probability: 25,
    expectedClosingDate: "2026-06-30",
    assignedSales: "Sara Nabil",
    pipelineStage: "Rejected",
    approvalStatus: "Rejected",
    statusTimestamps: {
      Draft: "2026-05-20T09:00:00.000Z",
      Sent: "2026-05-28T10:00:00.000Z",
      Opened: "2026-05-29T08:00:00.000Z",
      Rejected: "2026-06-12T14:00:00.000Z",
    },
    lastActivity: "2026-06-12T14:00:00.000Z",
    notes: "Lost to in-house team. Keep warm for Q4 catalog.",
    attachments: [],
    currentVersion: 1,
    projectInfo: {
      title: "Nile Foods Catalog Refresh",
      workspaceId: "product",
      shootDate: "2026-07-01",
      deliveryDate: "2026-07-20",
    },
    services: ["Product photography"],
    items: [
      {
        id: "li-005a",
        name: "Pack shot set (40 SKUs)",
        quantity: 40,
        unitPrice: 900,
      },
      {
        id: "li-005b",
        name: "Lifestyle set",
        quantity: 8,
        unitPrice: 1500,
      },
    ],
    optionalItems: [],
    discount: { type: "percent", value: 0 },
    taxRate: 14,
    timeline: {
      shootDate: "2026-07-01",
      finalDeliveryDate: "2026-07-20",
    },
    deliverables: ["Retouched pack shots", "Lifestyle selects"],
    paymentPlan: [
      {
        id: "pp-005a",
        label: "Deposit",
        percent: 50,
        amount: 24000,
        dueLabel: "On approval",
      },
      {
        id: "pp-005b",
        label: "Final",
        percent: 50,
        amount: 24000,
        dueLabel: "On delivery",
      },
    ],
    terms: DEFAULT_TERMS_COMMERCIAL,
    builderNotes: "",
    versions: [],
    createdAt: "2026-05-20T09:00:00.000Z",
    updatedAt: "2026-06-12T14:00:00.000Z",
  },
  {
    id: "quot-006",
    number: "QT-2026-0006",
    clientId: "client-013",
    clientName: "Palm Hills Developments",
    company: "Palm Hills Developments",
    contactName: "Yara Mansour",
    contactEmail: "marketing@palmhills.com",
    segment: "commercial",
    category: "Real estate film",
    estimatedValue: 260000,
    probability: 90,
    expectedClosingDate: "2026-07-12",
    assignedSales: "Ahmed Hassan",
    pipelineStage: "Approved",
    approvalStatus: "Approved",
    statusTimestamps: {
      Draft: "2026-06-01T09:00:00.000Z",
      "Waiting Review": "2026-06-08T10:00:00.000Z",
      Sent: "2026-06-10T12:00:00.000Z",
      Opened: "2026-06-11T09:00:00.000Z",
      Negotiation: "2026-06-18T15:00:00.000Z",
      Approved: "2026-07-02T11:00:00.000Z",
    },
    lastActivity: "2026-07-02T11:00:00.000Z",
    notes: "Approved. Awaiting deposit transfer to convert.",
    attachments: [],
    currentVersion: 2,
    projectInfo: {
      title: "Palm Hills — New Phase Film",
      location: "Future City",
      shootDate: "2026-08-05",
      deliveryDate: "2026-09-01",
      workspaceId: "rtm",
    },
    services: ["Aerial", "Architecture film", "Stills"],
    items: [
      {
        id: "li-006a",
        name: "Aerial + architecture shoot day",
        quantity: 2,
        unitPrice: 65000,
      },
      {
        id: "li-006b",
        name: "Edit + color package",
        quantity: 1,
        unitPrice: 90000,
      },
      {
        id: "li-006c",
        name: "Still photography day",
        quantity: 1,
        unitPrice: 40000,
      },
    ],
    optionalItems: [],
    discount: { type: "fixed", value: 10000 },
    taxRate: 14,
    timeline: {
      shootDate: "2026-08-05",
      finalDeliveryDate: "2026-09-01",
    },
    deliverables: ["90s film", "30s cutdown", "40 stills"],
    paymentPlan: [
      {
        id: "pp-006a",
        label: "Deposit",
        percent: 40,
        amount: 104000,
        dueLabel: "On approval",
      },
      {
        id: "pp-006b",
        label: "Final",
        percent: 60,
        amount: 156000,
        dueLabel: "On delivery",
      },
    ],
    terms: DEFAULT_TERMS_COMMERCIAL,
    builderNotes: "",
    versions: [],
    createdAt: "2026-06-01T09:00:00.000Z",
    updatedAt: "2026-07-02T11:00:00.000Z",
  },
  {
    id: "quot-007",
    number: "QT-2026-0007",
    clientId: "client-004",
    clientName: "Nour Hassan",
    contactName: "Nour Hassan",
    contactPhone: "+20 115 332 8899",
    contactEmail: "nour.hassan@email.com",
    segment: "wedding",
    category: "Wedding day",
    estimatedValue: 68000,
    probability: 95,
    expectedClosingDate: "2026-07-08",
    assignedSales: "Layla Mansour",
    pipelineStage: "Deposit Received",
    approvalStatus: "Deposit Received",
    statusTimestamps: {
      Draft: "2026-06-10T10:00:00.000Z",
      Sent: "2026-06-15T12:00:00.000Z",
      Approved: "2026-06-28T16:00:00.000Z",
      "Deposit Received": "2026-07-08T10:00:00.000Z",
    },
    lastActivity: "2026-07-08T10:00:00.000Z",
    notes: "Deposit confirmed. Ready to convert to project.",
    attachments: [],
    currentVersion: 1,
    projectInfo: {
      title: "Nour Hassan Wedding",
      location: "Marriott Mirage, Sharm",
      shootDate: "2026-10-10",
      deliveryDate: "2026-12-01",
      workspaceId: "weddings",
    },
    services: ["Photo", "Video"],
    items: [
      {
        id: "li-007a",
        name: "Wedding day photo + video",
        quantity: 1,
        unitPrice: 58000,
      },
      {
        id: "li-007b",
        name: "Travel package (Sharm)",
        quantity: 1,
        unitPrice: 10000,
      },
    ],
    optionalItems: [],
    discount: { type: "percent", value: 0 },
    taxRate: 0,
    timeline: {
      shootDate: "2026-10-10",
      finalDeliveryDate: "2026-12-01",
    },
    deliverables: ["Gallery", "Highlight film"],
    paymentPlan: [
      {
        id: "pp-007a",
        label: "Deposit",
        percent: 40,
        amount: 27200,
        dueLabel: "Received",
      },
      {
        id: "pp-007b",
        label: "Final",
        percent: 60,
        amount: 40800,
        dueLabel: "Before delivery",
      },
    ],
    terms: DEFAULT_TERMS_WEDDING,
    builderNotes: "",
    versions: [],
    createdAt: "2026-06-10T10:00:00.000Z",
    updatedAt: "2026-07-08T10:00:00.000Z",
  },
  {
    id: "quot-008",
    number: "QT-2026-0008",
    clientId: "client-006",
    clientName: "TechVentures Egypt",
    company: "TechVentures Egypt",
    contactName: "Rania Saleh",
    contactEmail: "events@techventures.eg",
    segment: "commercial",
    category: "Event coverage",
    estimatedValue: 55000,
    probability: 60,
    expectedClosingDate: "2026-07-18",
    assignedSales: "Karim Fouad",
    pipelineStage: "Revision",
    approvalStatus: "Negotiation",
    statusTimestamps: {
      Draft: "2026-06-20T09:00:00.000Z",
      Sent: "2026-06-25T11:00:00.000Z",
      Opened: "2026-06-26T08:00:00.000Z",
      Negotiation: "2026-07-03T14:00:00.000Z",
    },
    lastActivity: "2026-07-03T14:00:00.000Z",
    notes: "Client requested fewer hours; revising crew package.",
    attachments: [],
    currentVersion: 2,
    projectInfo: {
      title: "TechVentures Summit Coverage",
      location: "AUC New Cairo",
      shootDate: "2026-08-15",
      deliveryDate: "2026-08-25",
      workspaceId: "events",
    },
    services: ["Event photo", "Highlight reel"],
    items: [
      {
        id: "li-008a",
        name: "Full-day event coverage",
        quantity: 1,
        unitPrice: 35000,
      },
      {
        id: "li-008b",
        name: "Same-week highlight reel",
        quantity: 1,
        unitPrice: 20000,
      },
    ],
    optionalItems: [
      {
        id: "li-008o",
        name: "Live social selects (same day)",
        quantity: 1,
        unitPrice: 8000,
      },
    ],
    discount: { type: "percent", value: 0 },
    taxRate: 14,
    timeline: {
      shootDate: "2026-08-15",
      finalDeliveryDate: "2026-08-25",
    },
    deliverables: ["Edited gallery", "60–90s reel"],
    paymentPlan: [
      {
        id: "pp-008a",
        label: "Deposit",
        percent: 50,
        amount: 27500,
        dueLabel: "On approval",
      },
      {
        id: "pp-008b",
        label: "Final",
        percent: 50,
        amount: 27500,
        dueLabel: "On delivery",
      },
    ],
    terms: DEFAULT_TERMS_COMMERCIAL,
    builderNotes: "",
    versions: [],
    createdAt: "2026-06-20T09:00:00.000Z",
    updatedAt: "2026-07-03T14:00:00.000Z",
  },
  {
    id: "quot-009",
    number: "QT-2026-0009",
    clientName: "Bloom Cosmetics",
    company: "Bloom Cosmetics",
    contactName: "Farida Samir",
    contactPhone: "+20 100 888 2211",
    contactEmail: "farida@bloomcosmetics.eg",
    segment: "commercial",
    category: "Beauty campaign",
    estimatedValue: 0,
    probability: 20,
    expectedClosingDate: "2026-08-15",
    assignedSales: "Sara Nabil",
    pipelineStage: "New Inquiry",
    approvalStatus: "Draft",
    statusTimestamps: {
      Draft: "2026-07-09T08:00:00.000Z",
    },
    lastActivity: "2026-07-09T08:00:00.000Z",
    notes: "Inbound Instagram inquiry. Schedule discovery call.",
    attachments: [],
    currentVersion: 1,
    projectInfo: {
      title: "Bloom Cosmetics Campaign",
      workspaceId: "fashion",
    },
    services: [],
    items: [],
    optionalItems: [],
    discount: { type: "percent", value: 0 },
    taxRate: 14,
    timeline: {},
    deliverables: [],
    paymentPlan: [],
    terms: DEFAULT_TERMS_COMMERCIAL,
    builderNotes: "",
    versions: [],
    createdAt: "2026-07-09T08:00:00.000Z",
    updatedAt: "2026-07-09T08:00:00.000Z",
  },
  {
    id: "quot-010",
    number: "QT-2026-0010",
    clientId: "client-012",
    clientName: "Cairo Fashion Week",
    company: "Cairo Fashion Week",
    contactName: "Mona El-Kady",
    contactEmail: "production@cairofashionweek.com",
    segment: "commercial",
    category: "Runway coverage",
    estimatedValue: 140000,
    probability: 100,
    expectedClosingDate: "2026-05-01",
    assignedSales: "Karim Fouad",
    pipelineStage: "Converted to Project",
    approvalStatus: "Converted",
    statusTimestamps: {
      Draft: "2026-03-01T09:00:00.000Z",
      Sent: "2026-03-10T10:00:00.000Z",
      Approved: "2026-03-20T12:00:00.000Z",
      "Deposit Received": "2026-03-25T09:00:00.000Z",
      Converted: "2026-03-26T11:00:00.000Z",
    },
    lastActivity: "2026-03-26T11:00:00.000Z",
    notes: "Converted to PRJ-2026-0012.",
    attachments: [],
    currentVersion: 1,
    projectInfo: {
      title: "Cairo Fashion Week 2026",
      location: "AUC Greek Campus",
      shootDate: "2026-04-18",
      deliveryDate: "2026-05-05",
      workspaceId: "fashion",
    },
    services: ["Runway photo", "Backstage", "Highlights"],
    items: [
      {
        id: "li-010a",
        name: "Multi-day runway coverage",
        quantity: 3,
        unitPrice: 35000,
      },
      {
        id: "li-010b",
        name: "Highlight edit package",
        quantity: 1,
        unitPrice: 35000,
      },
    ],
    optionalItems: [],
    discount: { type: "percent", value: 0 },
    taxRate: 14,
    timeline: {
      shootDate: "2026-04-18",
      finalDeliveryDate: "2026-05-05",
    },
    deliverables: ["Runway galleries", "Event highlight"],
    paymentPlan: [
      {
        id: "pp-010a",
        label: "Deposit",
        percent: 50,
        amount: 70000,
        dueLabel: "Received",
      },
      {
        id: "pp-010b",
        label: "Final",
        percent: 50,
        amount: 70000,
        dueLabel: "On delivery",
      },
    ],
    terms: DEFAULT_TERMS_COMMERCIAL,
    builderNotes: "",
    convertedProjectId: "PRJ-2026-0012",
    convertedOrderId: "SODA-2026-0012",
    convertedClientId: "client-012",
    versions: [],
    createdAt: "2026-03-01T09:00:00.000Z",
    updatedAt: "2026-03-26T11:00:00.000Z",
  },
  {
    id: "quot-011",
    number: "QT-2026-0011",
    clientId: "client-003",
    clientName: "Galaxy Company",
    company: "Galaxy Company",
    contactName: "Hassan Nabil",
    contactEmail: "marketing@galaxy-eg.com",
    segment: "commercial",
    category: "Social content retainer",
    estimatedValue: 90000,
    probability: 50,
    expectedClosingDate: "2026-07-22",
    assignedSales: "Sara Nabil",
    pipelineStage: "Draft",
    approvalStatus: "Draft",
    statusTimestamps: {
      Draft: "2026-07-04T10:00:00.000Z",
    },
    lastActivity: "2026-07-08T12:00:00.000Z",
    notes: "Building monthly retainer quote for Q3 social.",
    attachments: [],
    currentVersion: 1,
    projectInfo: {
      title: "Galaxy Q3 Social Retainer",
      workspaceId: "rtm",
      categoryDetail: "Monthly content",
    },
    services: ["Photo", "Short-form video"],
    items: [
      {
        id: "li-011a",
        name: "Monthly content day",
        quantity: 3,
        unitPrice: 22000,
      },
      {
        id: "li-011b",
        name: "Edit + cutdowns package",
        quantity: 3,
        unitPrice: 8000,
      },
    ],
    optionalItems: [],
    discount: { type: "percent", value: 0 },
    taxRate: 14,
    timeline: {
      notes: "Three shoot days across July–September.",
    },
    deliverables: ["12 stills / month", "6 short videos / month"],
    paymentPlan: [
      {
        id: "pp-011a",
        label: "Monthly",
        percent: 100,
        amount: 90000,
        dueLabel: "Net 15",
      },
    ],
    terms: DEFAULT_TERMS_COMMERCIAL,
    builderNotes: "",
    versions: [],
    createdAt: "2026-07-04T10:00:00.000Z",
    updatedAt: "2026-07-08T12:00:00.000Z",
  },
];

// Attach initial version history snapshots
for (const q of mockQuotations) {
  if (q.versions.length === 0) {
    q.versions.push(
      version(1, q.assignedSales, q.createdAt, "Initial version created", q)
    );
    if (q.currentVersion >= 2) {
      q.versions.push(
        version(
          2,
          q.assignedSales,
          q.updatedAt,
          "Revised pricing and scope",
          q
        )
      );
    }
    if (q.currentVersion >= 3) {
      q.versions.push(
        version(
          3,
          "Junior Soda",
          q.updatedAt,
          "Updated optional items after client feedback",
          q
        )
      );
    }
  }
}
