/** Egyptian Arabic labels for SODA Connect chrome. */

export const CL = {
  title: "SODA Connect",
  search: "دور على محادثة، رسالة، أو ملف…",
  searchInChat: "دور جوه الشات…",
  recent: "آخر المحادثات",
  online: "أونلاين دلوقتي",
  groups: "محادثات الفريق",
  teamRoom: "SODA Team",
  emptyInbox: "اختار محادثة وابدأ تكلم الفريق.",
  emptyThread: "مفيش رسائل لسه — ابعت أول رسالة.",
  typePlaceholder: "اكتب رسالة…",
  reply: "رد",
  forward: "تحويل",
  copy: "نسخ",
  edit: "تعديل",
  deleteMe: "احذف عندي",
  deleteEveryone: "احذف للكل",
  pin: "تثبيت",
  unpin: "إلغاء التثبيت",
  star: "نجمة",
  unstar: "إزالة النجمة",
  info: "معلومات",
  shared: "مشترك",
  files: "ملفات",
  media: "ميديا",
  links: "لينكات",
  lastSeen: "آخر ظهور",
  status: "الحالة",
  activeNow: "نشط دلوقتي",
  typing: "بيكتب…",
  recording: "بيسجّل صوت…",
  uploading: "بيرفع ملف…",
  onlineStatus: "أونلاين",
  away: "بعيد",
  busy: "مشغول",
  offline: "أوفلاين",
  send: "إرسال",
  holdVoice: "اضغط واستمر للتسجيل",
  discardVoice: "امسح التسجيل",
  dropFiles: "سيّب الملفات هنا",
  uploadProgress: "جاري الرفع…",
  forwarded: "محوّلة",
  edited: "معدّلة",
  deleted: "تم حذف الرسالة",
  pinnedBanner: "رسالة مثبتة",
  unread: "غير مقروء",
  loadOlder: "حمّل رسائل أقدم",
  noResults: "مفيش نتائج",
  callsStub: "المكالمات قريب — مش متاحة في الـ MVP",
  channelsStub: "القنوات / البوتات / AI — لاحقاً",
  you: "أنت",
  everyone: "الكل",
  presenceCustom: "حالة مخصصة",
  markRead: "اتقرت",
  playback: "سرعة التشغيل",
} as const;
