import type { Workspace, WorkspaceSubcategory } from "@/lib/taxonomy/types";

export const seedWorkspaces: Workspace[] = [
  {
    id: "rtm",
    label: "RTM",
    slug: "rtm",
    description: "Real-time marketing and content production",
    icon: "radio",
    order: 1,
    isActive: true,
    hasSubcategories: true,
    color: "#6366f1",
  },
  {
    id: "weddings",
    label: "Weddings",
    slug: "weddings",
    description: "Wedding and engagement photography & film",
    icon: "heart",
    order: 2,
    isActive: true,
    hasSubcategories: true,
    color: "#ec4899",
  },
  {
    id: "fashion",
    label: "Fashion",
    slug: "fashion",
    description: "Fashion editorials, lookbooks, and portraits",
    icon: "shirt",
    order: 3,
    isActive: true,
    hasSubcategories: false,
    color: "#a855f7",
  },
  {
    id: "product",
    label: "Product",
    slug: "product",
    description: "Product and e-commerce photography",
    icon: "package",
    order: 4,
    isActive: true,
    hasSubcategories: false,
    color: "#f59e0b",
  },
  {
    id: "events",
    label: "Events",
    slug: "events",
    description: "Corporate events, summits, and live coverage",
    icon: "calendar",
    order: 5,
    isActive: true,
    hasSubcategories: false,
    color: "#10b981",
  },
  {
    id: "commercial",
    label: "Commercial",
    slug: "commercial",
    description: "Brand campaigns and corporate content",
    icon: "briefcase",
    order: 6,
    isActive: true,
    hasSubcategories: true,
    color: "#3b82f6",
  },
];

export const seedSubcategories: WorkspaceSubcategory[] = [
  // RTM
  {
    id: "rtm-future-city",
    workspaceId: "rtm",
    label: "Future City",
    slug: "future-city",
    order: 1,
    isActive: true,
  },
  {
    id: "rtm-daily-work",
    workspaceId: "rtm",
    label: "Daily Work",
    slug: "daily-work",
    order: 2,
    isActive: true,
  },
  {
    id: "rtm-partner-projects",
    workspaceId: "rtm",
    label: "Partner Projects",
    slug: "partner-projects",
    order: 3,
    isActive: true,
  },
  {
    id: "rtm-internal",
    workspaceId: "rtm",
    label: "Internal",
    slug: "internal",
    order: 4,
    isActive: true,
  },
  // Weddings
  {
    id: "weddings-upcoming",
    workspaceId: "weddings",
    label: "Upcoming Weddings",
    slug: "upcoming-weddings",
    order: 1,
    isActive: true,
  },
  {
    id: "weddings-delivered",
    workspaceId: "weddings",
    label: "Delivered Weddings",
    slug: "delivered-weddings",
    order: 2,
    isActive: true,
  },
  // Commercial
  {
    id: "commercial-campaigns",
    workspaceId: "commercial",
    label: "Campaigns",
    slug: "campaigns",
    order: 1,
    isActive: true,
  },
  {
    id: "commercial-corporate",
    workspaceId: "commercial",
    label: "Corporate",
    slug: "corporate",
    order: 2,
    isActive: true,
  },
  {
    id: "commercial-social-media",
    workspaceId: "commercial",
    label: "Social Media",
    slug: "social-media",
    order: 3,
    isActive: true,
  },
];
