import type { EquipmentAssignment, EquipmentItem } from "@/lib/equipment/types";

export const mockEquipment: EquipmentItem[] = [
  {
    id: "eq-cam-01",
    name: "Sony A7IV Body A",
    type: "Camera",
    serialNumber: "SN-A7IV-001",
    status: "assigned",
    acquiredAt: "2024-01-15",
  },
  {
    id: "eq-cam-02",
    name: "Sony FX3 Body B",
    type: "Camera",
    serialNumber: "SN-FX3-002",
    status: "assigned",
    acquiredAt: "2024-03-01",
  },
  {
    id: "eq-lens-01",
    name: "GM 24-70mm f/2.8",
    type: "Lens",
    serialNumber: "SN-2470-01",
    status: "assigned",
    acquiredAt: "2024-01-15",
  },
  {
    id: "eq-lens-02",
    name: "GM 70-200mm f/2.8",
    type: "Lens",
    serialNumber: "SN-70200-01",
    status: "available",
    acquiredAt: "2024-02-20",
  },
  {
    id: "eq-drone-01",
    name: "DJI Mavic 3 Cine",
    type: "Drone",
    serialNumber: "SN-M3C-01",
    status: "assigned",
    acquiredAt: "2024-05-01",
  },
  {
    id: "eq-laptop-01",
    name: "MacBook Pro 16 M3 — Edit 1",
    type: "Laptop",
    serialNumber: "SN-MBP-01",
    status: "assigned",
    acquiredAt: "2024-06-10",
  },
  {
    id: "eq-mon-01",
    name: "ASUS ProArt 27\"",
    type: "Monitor",
    serialNumber: "SN-PA27-01",
    status: "assigned",
    acquiredAt: "2024-06-10",
  },
  {
    id: "eq-ssd-01",
    name: "Samsung T7 2TB — Shuttle A",
    type: "SSD",
    status: "assigned",
    acquiredAt: "2024-07-01",
  },
  {
    id: "eq-ssd-02",
    name: "Samsung T7 2TB — Shuttle B",
    type: "SSD",
    status: "available",
    acquiredAt: "2024-07-01",
  },
  {
    id: "eq-light-01",
    name: "Aputure 600d Kit",
    type: "Lighting",
    serialNumber: "SN-AP600-01",
    status: "assigned",
    acquiredAt: "2024-04-01",
  },
  {
    id: "eq-acc-01",
    name: "Rode Wireless GO II",
    type: "Accessories",
    status: "assigned",
    acquiredAt: "2024-08-01",
  },
  {
    id: "eq-acc-02",
    name: "Manfrotto Tripod Carbon",
    type: "Accessories",
    status: "available",
    acquiredAt: "2023-11-01",
  },
];

export const mockEquipmentAssignments: EquipmentAssignment[] = [
  {
    id: "ea-01",
    equipmentId: "eq-cam-01",
    personId: "tm-sara",
    assignedAt: "2025-11-01",
    note: "Primary stills body",
  },
  {
    id: "ea-02",
    equipmentId: "eq-cam-02",
    personId: "tm-karim",
    assignedAt: "2025-12-01",
    note: "A-cam motion",
  },
  {
    id: "ea-03",
    equipmentId: "eq-lens-01",
    personId: "tm-sara",
    assignedAt: "2025-11-01",
  },
  {
    id: "ea-04",
    equipmentId: "eq-drone-01",
    personId: "tm-omar",
    assignedAt: "2026-01-15",
  },
  {
    id: "ea-05",
    equipmentId: "eq-laptop-01",
    personId: "tm-layla",
    assignedAt: "2025-10-01",
  },
  {
    id: "ea-06",
    equipmentId: "eq-mon-01",
    personId: "tm-layla",
    assignedAt: "2025-10-01",
  },
  {
    id: "ea-07",
    equipmentId: "eq-ssd-01",
    personId: "tm-ahmed",
    assignedAt: "2026-06-01",
    note: "Producer shuttle — July jobs",
  },
  {
    id: "ea-08",
    equipmentId: "eq-light-01",
    personId: "tm-youssef",
    assignedAt: "2026-03-01",
  },
  {
    id: "ea-09",
    equipmentId: "eq-acc-01",
    personId: "tm-karim",
    assignedAt: "2026-02-01",
  },
  // History — returned
  {
    id: "ea-10",
    equipmentId: "eq-ssd-02",
    personId: "tm-nora",
    assignedAt: "2026-01-01",
    returnedAt: "2026-04-30",
    note: "Wedding season shuttle — returned",
  },
  {
    id: "ea-11",
    equipmentId: "eq-cam-01",
    personId: "tm-nora",
    assignedAt: "2025-06-01",
    returnedAt: "2025-10-31",
    note: "Second shooter body — returned to Sara",
  },
];
